name: to_do_list
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  expandable: ^5.0.1
  flutter_modular: ^5.0.3
  flutter_svg: ^2.0.7
  realm: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
    assets:
     - assets/images/
     - assets/icons/
     - assets/launcher/

    fonts:
    - family: Poppins
      fonts:
        - asset: lib/src/theme/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: lib/src/theme/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: lib/src/theme/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: lib/src/theme/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: lib/src/theme/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/src/theme/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/src/theme/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/src/theme/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: lib/src/theme/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: lib/src/theme/fonts/poppins/Poppins-Italic.ttf
          style: italic


